- name: Install rsync
  apt:
    pkg=rsync
    update_cache=yes
    cache_valid_time={{APT_CACHE_VALID_TIME}}
    state=present

- name: Check whether wp is installed
  stat: path={{wordpress_webroot}}/wp-content
  register: wp_present

- name: Sync git repo for the site
  git:
    repo: "{{synced_wordpress.repo}}"
    dest: "{{wordpress_site_dir}}"
    version: HEAD
  when: synced_wordpress.repo is defined

- name: Copy files in place
  synchronize: src={{wordpress_files}}/ dest={{wordpress_webroot}} delete=yes
  when: wp_present.stat.exists == false and wordpress_files is defined

- name: Install wp-config.php
  template:
    src={{item}}
    dest={{wordpress_webroot}}/wp-config.php
  with_first_found:
        - files:
            - "{{wordpress_config_template}}"
          paths:
            - "{{wordpress_assets_path}}"
            - "../templates"
  when: wordpress_config_template is defined

# for some reason this does not replace (manually running works)
- name: Replace site name
  debug: msg="wp --allow-root search-replace {{wordpress_db.site_name}} {{site_name}} chdir={{wordpress_webroot}}"
  # shell: /usr/local/bin/wp --allow-root search-replace {{wordpress_db.site_name}} {{site_name}} chdir={{wordpress_webroot}}
  when: wp_present.stat.exists == false and wordpress_db.site_name is defined and wordpress_db.site_name != site_name
